artifacts_root : "artifacts"

Data_Ingestion:
  root_dir : "artifacts/data_ingestion/"
  text_path : "artifacts/data_ingestion/raw_text/"
  token_path : "artifacts/data_ingestion/tokens/tokens.csv"
  
  

Data_Transformation:
  root_dir : "artifacts/data_transformation/"
  chunks_path : "artifacts/data_ingestion/tokens/tokens.csv"
  embedded_vectors_path : "artifacts/data_transformation/embedded_vectors/vectors.csv"
  

